// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBManagementAPI.Models;

#nullable disable

namespace OBManagementAPI.Migrations
{
    [DbContext(typeof(ObmanagementContext))]
    [Migration("20260927074437_AddGeofenceAndSubstituteSchema")]
    partial class AddGeofenceAndSubstituteSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OBManagementAPI.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC07BB7B523E");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.ArrivalDepartureTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FacultyAccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyAccountId");

                    b.ToTable("ArrivalDepartureTasks", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.BuildingFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Building__3214EC070E414C38");

                    b.ToTable("BuildingFloor", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyGeofenceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyAccountId")
                        .HasColumnType("int");

                    b.Property<int>("GeofenceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrentlyInside")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("FacultyAccountId");

                    b.HasIndex("GeofenceId");

                    b.ToTable("FacultyGeofenceState", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyMemberOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyAccountId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__FacultyM__3214EC07CEFD6BEC");

                    b.HasIndex("FacultyAccountId");

                    b.HasIndex("OfficeId");

                    b.ToTable("FacultyMemberOffice", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FacultyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("GeofenceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInsideGeofence")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("FacultyAccountId");

                    b.HasIndex("GeofenceId");

                    b.ToTable("FacultyTracking", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Geofence", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficeBoyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubstituteAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubstituteOfficeBoyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorAccountId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeBoyAccountId");

                    b.HasIndex("SubstituteOfficeBoyAccountId");

                    b.HasIndex("SupervisorAccountId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC076A76558D");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingFloorId")
                        .HasColumnType("int");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Office__3214EC07AE5D7385");

                    b.HasIndex("BuildingFloorId");

                    b.ToTable("Office", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.OfficeBoyAssignedFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeBoyAccountId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__OfficeBo__3214EC072AB34896");

                    b.HasIndex("FloorId");

                    b.HasIndex("OfficeBoyAccountId");

                    b.HasIndex("OfficeId");

                    b.ToTable("OfficeBoyAssignedFloors", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FacultyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("GeofenceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToOfficeBoy")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficeBoyAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("TaskCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TaskTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TriggerType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Task__3214EC07C2FACE9A");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("FacultyAccountId");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OfficeBoyAccountId");

                    b.HasIndex("TaskCategoryId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.TaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TaskCategory", (string)null);
                });

            modelBuilder.Entity("OBManagementAPI.Models.ArrivalDepartureTask", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Account", "FacultyAccount")
                        .WithMany("ArrivalDepartureTasks")
                        .HasForeignKey("FacultyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyAccount");
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyGeofenceState", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Account", "FacultyAccount")
                        .WithMany("FacultyGeofenceStates")
                        .HasForeignKey("FacultyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyGeofenceState_Account");

                    b.HasOne("OBManagementAPI.Models.Geofence", "Geofence")
                        .WithMany("FacultyGeofenceStates")
                        .HasForeignKey("GeofenceId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyGeofenceState_Geofence");

                    b.Navigation("FacultyAccount");

                    b.Navigation("Geofence");
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyMemberOffice", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Account", "FacultyAccount")
                        .WithMany("FacultyMemberOffices")
                        .HasForeignKey("FacultyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__FacultyMe__Facul__5165187F");

                    b.HasOne("OBManagementAPI.Models.Office", "Office")
                        .WithMany("FacultyMemberOffices")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("FK__FacultyMe__Offic__52593CB8");

                    b.Navigation("FacultyAccount");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OBManagementAPI.Models.FacultyTracking", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Account", "FacultyAccount")
                        .WithMany("FacultyTrackings")
                        .HasForeignKey("FacultyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_FacultyTracking_Account");

                    b.HasOne("OBManagementAPI.Models.Geofence", "Geofence")
                        .WithMany("FacultyTrackings")
                        .HasForeignKey("GeofenceId")
                        .HasConstraintName("FK_FacultyTracking_Geofence");

                    b.Navigation("FacultyAccount");

                    b.Navigation("Geofence");
                });

            modelBuilder.Entity("OBManagementAPI.Models.LeaveRequest", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Account", "OfficeBoyAccount")
                        .WithMany()
                        .HasForeignKey("OfficeBoyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBManagementAPI.Models.Account", "SubstituteOfficeBoyAccount")
                        .WithMany()
                        .HasForeignKey("SubstituteOfficeBoyAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OBManagementAPI.Models.Account", "SupervisorAccount")
                        .WithMany()
                        .HasForeignKey("SupervisorAccountId");

                    b.Navigation("OfficeBoyAccount");

                    b.Navigation("SubstituteOfficeBoyAccount");

                    b.Navigation("SupervisorAccount");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Office", b =>
                {
                    b.HasOne("OBManagementAPI.Models.BuildingFloor", "BuildingFloor")
                        .WithMany("Offices")
                        .HasForeignKey("BuildingFloorId")
                        .IsRequired()
                        .HasConstraintName("FK__Office__Building__4E88ABD4");

                    b.Navigation("BuildingFloor");
                });

            modelBuilder.Entity("OBManagementAPI.Models.OfficeBoyAssignedFloor", b =>
                {
                    b.HasOne("OBManagementAPI.Models.BuildingFloor", "Floor")
                        .WithMany("OfficeBoyAssignedFloors")
                        .HasForeignKey("FloorId")
                        .IsRequired()
                        .HasConstraintName("FK__OfficeBoy__Floor__5535A963");

                    b.HasOne("OBManagementAPI.Models.Account", "OfficeBoyAccount")
                        .WithMany("OfficeBoyAssignedFloors")
                        .HasForeignKey("OfficeBoyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__OfficeBoy__Offic__571DF1D5");

                    b.HasOne("OBManagementAPI.Models.Office", "Office")
                        .WithMany("OfficeBoyAssignedFloors")
                        .HasForeignKey("OfficeId")
                        .IsRequired()
                        .HasConstraintName("FK__OfficeBoy__Offic__5629CD9C");

                    b.Navigation("Floor");

                    b.Navigation("Office");

                    b.Navigation("OfficeBoyAccount");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Task", b =>
                {
                    b.HasOne("OBManagementAPI.Models.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .HasConstraintName("FK__Task__CurrentLocation");

                    b.HasOne("OBManagementAPI.Models.Account", "FacultyAccount")
                        .WithMany("TaskFacultyAccounts")
                        .HasForeignKey("FacultyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Task__FacultyAcc__5CD6CB2B");

                    b.HasOne("OBManagementAPI.Models.Geofence", "Geofence")
                        .WithMany("Tasks")
                        .HasForeignKey("GeofenceId")
                        .HasConstraintName("FK_Task_Geofence");

                    b.HasOne("OBManagementAPI.Models.Location", "Location")
                        .WithMany("Tasks")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Task__LocationId__5EBF139D");

                    b.HasOne("OBManagementAPI.Models.Account", "OfficeBoyAccount")
                        .WithMany("TaskOfficeBoyAccounts")
                        .HasForeignKey("OfficeBoyAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Task__OfficeBoyA__5DCAEF64");

                    b.HasOne("OBManagementAPI.Models.TaskCategory", "TaskCategory")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryId")
                        .HasConstraintName("FK_Task_TaskCategory");

                    b.Navigation("CurrentLocation");

                    b.Navigation("FacultyAccount");

                    b.Navigation("Geofence");

                    b.Navigation("Location");

                    b.Navigation("OfficeBoyAccount");

                    b.Navigation("TaskCategory");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Account", b =>
                {
                    b.Navigation("ArrivalDepartureTasks");

                    b.Navigation("FacultyGeofenceStates");

                    b.Navigation("FacultyMemberOffices");

                    b.Navigation("FacultyTrackings");

                    b.Navigation("OfficeBoyAssignedFloors");

                    b.Navigation("TaskFacultyAccounts");

                    b.Navigation("TaskOfficeBoyAccounts");
                });

            modelBuilder.Entity("OBManagementAPI.Models.BuildingFloor", b =>
                {
                    b.Navigation("OfficeBoyAssignedFloors");

                    b.Navigation("Offices");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Geofence", b =>
                {
                    b.Navigation("FacultyGeofenceStates");

                    b.Navigation("FacultyTrackings");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Location", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OBManagementAPI.Models.Office", b =>
                {
                    b.Navigation("FacultyMemberOffices");

                    b.Navigation("OfficeBoyAssignedFloors");
                });

            modelBuilder.Entity("OBManagementAPI.Models.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
